- name: Install packages - workstation - python (Archlinux)
  ansible.builtin.package:
    state: present
    name:
      # - pyenv # Installation verschoben nach packages_workstation-pythonEnv.yml # Easily switch between multiple versions of Python
      - python
      - python-pip # The PyPA recommended tool for installing Python packages
      - uv # fast Python package and project manager
  when: ansible_facts['distribution'] in ["Archlinux"]

- name: Install packages - workstation - python  (Debian)
  ansible.builtin.package:
    state: present
    name:
      - pipx # execute binaries from Python packages in isolated environments
      - python3
      - python3-pip
  when: ansible_facts['distribution'] == "Debian"
