# ###############################
# ### zsh plugins - from git repo
# ###############################
# - Anm.: bei Archlinux Ã¼ber paket, bei Manjaro schon von Werk aus vorhanden

- name: Zsh plugins install - zsh-autosuggestions (Debian)
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /usr/share/zsh/plugins/zsh-autosuggestions
    clone: true
    update: true
  when: ansible_facts['distribution'] in ["Debian"]

- name: Zsh plugins install - zsh-syntax-highlighting (Debian)
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /usr/share/zsh/plugins/zsh-syntax-highlighting
    clone: true
    update: true
  when: ansible_facts['distribution'] in ["Debian"]

- name: Zsh plugins install - zsh-history-substring-search (Debian)
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: /usr/share/zsh/plugins/zsh-history-substring-search
    clone: true
    update: true
  when: ansible_facts['distribution'] in ["Debian"]
