
### Ubuntu
- name: copy and decypt extensions-sync.json to users home-config (Ubuntu)
  copy:
#    src: files/extSync-Ubuntu/extensions-sync.json
    src: files/gnomeshellExtensions/ubuntu_extensions-sync.json
    dest: ~/.config/extensions-sync.json
    owner: sandro
    group: sandro
    mode: u=rw,g=rw,o=r
    decrypt: yes
  when:
    - env_desktop == "ubuntu:gnome"


### Archlinux, Manjaro
- name: copy and decypt extensions-sync.json to users home-config (Manjaro)
  copy:
#    src: files/extSync-Manjaro/extensions-sync.json
    src: files/gnomeshellExtensions/manjaro_extensions-sync
    dest: ~/.config/extensions-sync.json
    owner: sandro
    group: sandro
    mode: u=rw,g=rw,o=r
    decrypt: yes
  when:
    - ansible_distribution == "Archlinux"
    - env_desktop == "gnome"

### TODO: Suse

