- name: add ansible user
  tags: users
  user:
    name: s_ansible
    system: yes

- name: set up sudo for ansible user
  tags: users
  copy:
    src: files/sudoer_s_ansible
    dest: /etc/sudoers.d/s_ansible
    owner: root
    group: root
    mode: 0440
