#- name: install flatpak packages for workstations (all Distros)
#  tags: workstation,ubuntu,suse,arch,flatpak
#  flatpak:
#    name: ['de.willuhn.Jameica','io.atom.Atom']
#    state: present
#    method: system


- name: install flatpak packages for workstations (Ubuntu)
  tags: workstation,ubuntu,flatpak
  flatpak:
    name: '{{ item }}'
    state: present
    method: system
  with_items:
    - 'com.belmoussaoui.Authenticator'
    - 'com.discordapp.Discord'
    - 'com.github.johnfactotum.Foliate'
    - 'com.github.micahflee.torbrowser-launcher'
#    - 'com.ulduzsoft.Birdtray'  --> evolution
    - 'de.willuhn.Jameica'
    - 'io.atom.Atom'
    - 'net.cozic.joplin_desktop'
    - 'org.chromium.Chromium'
    - 'org.jitsi.jitsi-meet'
#    - 'org.ksnip.ksnip' # eher kde
    - 'org.libreoffice.LibreOffice'
#    - 'org.mozilla.Thunderbird' --> evolution
    - 'org.signal.Signal'
  when:
    - ansible_distribution in ["Ubuntu"]


- name: install flatpak packages for workstations (Archlinux)
  tags: workstation,arch,flatpak
  flatpak:
    name: '{{ item }}'
    state: present
    method: system
  with_items:
    - 'com.belmoussaoui.Authenticator'
#    - 'com.discordapp.Discord'
#    - 'com.github.johnfactotum.Foliate'
#    - 'com.github.micahflee.torbrowser-launcher'
    - 'com.ulduzsoft.Birdtray'
    - 'de.willuhn.Jameica'
#    - 'io.atom.Atom'
    - 'net.cozic.joplin_desktop'
#    - 'org.chromium.Chromium'
    - 'org.jitsi.jitsi-meet'
#    - 'org.ksnip.ksnip'
#    - 'org.libreoffice.LibreOffice'
#    - 'org.mozilla.Thunderbird'
#    - 'org.signal.Signal'
  when:
    - ansible_distribution in ["Archlinux"]


- name: install flatpak packages for workstations (Suse)
  tags: workstation,suse,flatpak
  flatpak:
    name: '{{ item }}'
    state: present
    method: system
  with_items:
    - 'com.belmoussaoui.Authenticator'
#    - 'com.ulduzsoft.Birdtray' # -> evolution
#    - 'com.nextcloud.desktopclient.nextcloud'
    - 'de.willuhn.Jameica'
    - 'io.atom.Atom'
    - 'net.cozic.joplin_desktop'
    - 'org.jitsi.jitsi-meet'
    - 'org.signal.Signal'
  when:
#    - ansible_distribution == "openSUSE Leap"
    - ansible_os_family == "Suse"

