# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml

# Customizing the prompt (including desired modules at desired position and sequence):
format = """
[â•­â•´](fg:#505050)\
$os\
$username\
$hostname\
$sudo\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
\
$kubernetes$vcsh$fossil_branch$hg_branch$pijul_channel$docker_context$package$c\
$cmake$cobol$daml$dart$deno$dotneti$elixir$ulm$erlang$fennel$golang$guix_shell\
$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$php\
$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$swift$terraform$vlang\
$vagrant$zig$buf$nix_shell$conda$meson$spack$aws$gcloud$openstack$azure$crystal\
$container$shell$env_var$battery$custom\
\
$jobs\
$memory_usagetime\
[î‚° ](fg:#242424)\
$cmd_duration\
$fill\
$line_break\
[â•°â•´](fg:#505050)\
[$status\
$localip\
$character]($style)\
"""

# - '$line_break', i.e. everything from the next line on refers to the second line of the prompt.
#   - '\n' for a line break could work too on your system, but it is just not a 'starship' module. 
#   - Just let the module do the correct line break.
# - Some modules listed above will not show up (all the time), as their default value is 'disabled = true' or
#   they are only displayed under certain conditions.
#   They have to be enabled manually, e.g. see below "# Customizing and enabling some modules used above"
#   https://starship.rs/config/

# Don't be confused if you see this toml file via web browser on Starship website, gist, ... and you don't see any "real" symbols here.
# If Nerd-fonts are already installed on your system (e.g. MesloLG Nerd Font, FiraCode Nerd Font, ...) it should work


# Inserts a blank line between shell prompts:
add_newline = true

# Customization and activation of some modules:
# Listed in the order of their position in the module row above
[os]
format = "[î‚¶](fg:#242424)[$symbol ]($style)[î‚± ](fg:#707070 bold bg:#242424)"
style = "fg:#BBBBBB bg:#242424"
disabled = false

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ïŒƒ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "ğŸ‰" # "î†"
Emscripten = "ğŸ”—"
EndeavourOS = "ïŒ¢" # "ï»"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Garuda = "ï…¼"
Gentoo = "ïŒ"
HardenedBSD = "ï¦—"
Illumos = "ğŸ¦"
Linux = "ï…¼"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Mariner = "ï…¼"
MidnightBSD = "ğŸŒ˜"
Mint = "ïŒ"
NetBSD = "ï…¼"
NixOS = "ïŒ“"
OpenBSD = "ïŒ¨" # "ï…¼"
OpenCloudOS = "â˜ï¸"
openEuler = "ï…¼"
openSUSE = "ïŒ”"
OracleLinux = "âŠ‚âŠƒ"
Pop = "ïŒª" # "ï…¼"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Redox = "ğŸ§ª"
Solus = "ïŒ­" # "ï…¼ "
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ï„ˆ"
Windows = "îœ"

[username]
format = '[$user ]($style)'
style_user = 'fg:green bold bg:#242424'
style_root = 'fg:red bold bg:#242424'
show_always = false
disabled = false

[hostname]
format = '[$ssh_symbol](fg:green bold bg:#242424)[$hostname ](fg:green bold bg:#242424)[î‚± ](fg:green bold bg:#242424)'
ssh_only = true
ssh_symbol = 'î® ' # 'ï…½â‡’' # 'ï£· ' # 'ï¬â‡’'
#trim_at = '.companyname.com'
disabled = false

[sudo]
style = 'fg:red bold bg:#242424'
symbol = 'ï”„ â¯ ' # 'ï”Š â¯ '
disabled = false

[directory]
format = '[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)[](bg:#242424)[î‚±](fg:cyan bg:#242424)'
style = 'fg:cyan bold bg:#242424'
read_only_style = 'fg:cyan bg:#242424'
read_only = 'ï ½ ' # 'ï£­ ' # 'ï£® ''
home_symbol = 'ï€• ~'
truncation_length = 3
truncation_symbol = 'â€¦/'
truncate_to_repo = true
repo_root_style	= 'fg:cyan bold bg:#242424' #'fg:#E04D27 bold'
use_os_path_sep = true
disabled = false

[git_branch]
format = '[â¯ $symbol $branch(:$remote_branch) ]($style)'
style = 'fg:#E04D27 bg:#242424'
symbol = 'ï¡'
#ignore_branches = ['master', 'main']

[git_commit]
format = '[\($hash$tag\)]($style)'
style = 'fg:#E04D27 bg:#242424'
commit_hash_length = 8
tag_symbol = 'ï’ ' # 'ï€« ''
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\] ]($deleted_style)'
added_style = 'fg:#E04D27 bg:#242424'
deleted_style = 'fg:#E04D27 bg:#242424'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = 'fg:#E04D27 bg:#242424'
conflicted = '${count}ï‘¯ '
ahead = '${count}â‡¡ '
behind = '${count}â‡£ '
diverged = 'â‡•${ahead_count}â‡¡${behind_count}â‡£ '
up_to_date = 'âœ“ '
untracked = '[${count}ï³‡ ](fg:red bg:#242424)' # 'ï° ' # '? '
stashed = '[${count}ï›¢ ](fg:#A52A2A bg:#242424)' # 'ğŸ“¦ '# 'î› ' # 'ï’‡ ' # 'îœ ' # 'î¬‰ ' 
modified = '[${count}ó°·‰ ](fg:#C8AC00 bg:#242424)' # 'ğŸ“' # '! '
staged = '[${count}ïƒ‘ ](fg:green bg:#242424)' # '+ '
renamed = '${count}ï«¦ ' # 'ï—ˆ '
deleted = '${count}ï¯Š ' # 'ğŸ—‘ ' '- '
disabled = false

[jobs]
format = '[î‚± $number$symbol]($style) '
style = 'fg:blue bg:#242424'
symbol = 'ï¥­' # 'ïª‚' # 'ó°œ' # 'î®¢' # 'âœ¦'
symbol_threshold = 1
number_threshold = 4
disabled = false

[memory_usage]
format = '[î‚± $symbol ${ram} ${swap}]($style) '
style = 'fg:purple dimmed bg:#242424'
symbol = 'ï¬™ ï¥£' # 'ï¬™ ï§¥' # 'ï¬™ / ó°¾µ' # 'ó°› ó°¾µ' # 'ï¬™ ó°¾´' # 'ï¬™ ó°¾¶' # 'ï¬™ ó°¾·' 'ï¬™ ó°£‚'
threshold = 75
disabled = false

[cmd_duration]
format = '[î‚³ ï”Ÿ $duration]($style) '
style = 'fg:yellow'
min_time = 500
disabled = false

[fill]
style = 'fg:#505050'
symbol = 'â”€'

[status]
format = '[$symbol$status $hex_status ï–› $signal_number-$signal_name]($style) '
style = 'fg:red'
symbol = 'âœ˜ '
disabled = false

[localip]
format = '[$localipv4](fg:green bold) '
ssh_only = true
disabled = false
