# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml
#
# ### Variant 2: two line prompt, no background in top line, separators on left side
#
# - No filling solid line in top row: 
#   Replace '$fill\' with just one character '\' or just completely delete the line that contains '$fill\' further down.
#
# - '$line_break': everything from the next line on refers to the second line of the prompt.
#
# - Some modules listed further down will not show up (all the time), as their default value is 'disabled = true' or
#   they are only displayed under certain conditions.
#
# - Symbols:
#   Don't be confused if you see this toml file via web browser on a website, gist, ... and you don't see any "real" symbols further down.
#   If Nerd-fonts are already installed on your system (e.g. MesloLG Nerd Font, FiraCode Nerd Font, ...) it should work.


# Customizing the prompt (and placing desired modules at desired position and sequence):
format = """
[â•­â•´](fg:#505050)\
$os\
$username\
$hostname\
$sudo\
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$jobs\
$memory_usage\
[ ](fg:#242424)\
$cmd_duration\
$fill\
$line_break\
[â•°â•´](fg:#505050)\
[$status\
$localip\
$character]($style)
"""

# Inserts a blank line between shell prompts:
add_newline = true

# Customization and activation of some modules:
# Listed in the order of their position in the module row above
[os]
format = "[$symbol ]($style)[ ]()"
style = "fg:#AAAAAA"
disabled = false

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ïŒƒ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "ğŸ‰" # "î†"
Emscripten = "ğŸ”—"
EndeavourOS = "ïŒ¢" # "ï»"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Garuda = "ï…¼"
Gentoo = "ïŒ"
HardenedBSD = "ï¦—"
Illumos = "ğŸ¦"
Linux = "ï…¼"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Mariner = "ï…¼"
MidnightBSD = "ğŸŒ˜"
Mint = "ïŒ"
NetBSD = "ï…¼"
NixOS = "ïŒ“"
OpenBSD = "ïŒ¨" # "ï…¼"
OpenCloudOS = "â˜ï¸"
openEuler = "ï…¼"
openSUSE = "ïŒ”"
OracleLinux = "âŠ‚âŠƒ"
Pop = "ïŒª" # "ï…¼"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Redox = "ğŸ§ª"
Solus = "ïŒ­" # "ï…¼ "
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ï„ˆ"
Windows = "îœ"

[username]
format = '[î‚± ](fg:green bold)[$user]($style)[ ]()'
style_user = 'fg:green bold'
style_root = 'fg:red bold'
show_always = false
disabled = false

[hostname]
format = '[$ssh_symbol ](fg:green bold)[$hostname](fg:green bold)[ ]()'
ssh_only = true
ssh_symbol = 'î®' # 'ï…½â‡’' # 'ï£· ' # 'ï¬â‡’'
#trim_at = '.companyname.com'
disabled = false

[sudo]
format = '[î‚± ](fg:red bold)[as $symbol]($style)'
style = 'fg:red bold'
symbol = 'ï”„ ' # 'ï”Š â¯ '
disabled = false

[directory]
format = '[î‚± ](fg:cyan bold)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)'
style = 'fg:cyan bold'
home_symbol = 'ï€• ~'
read_only = 'ï ½ ' # 'ï£­ ' # 'ï£® ''
read_only_style = 'fg:cyan'
truncation_length = 3
truncation_symbol = 'â€¦/'
truncate_to_repo = true
repo_root_format = '[î‚± ](fg:cyan bold)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
repo_root_style	= 'fg:cyan bold'
use_os_path_sep = true
disabled = false

[git_branch]
format = '[â¯ $symbol $branch(:$remote_branch)]($style)[ ]()'
style = 'fg:#E04D27'
symbol = 'ï¡'
#ignore_branches = ['master', 'main']

[git_commit]
format = '[\($hash$tag\)]($style)[ ]()'
style = 'fg:#E04D27'
commit_hash_length = 8
tag_symbol = 'ï’ ' # 'ï€« ''
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ]()'
added_style = 'fg:#E04D27'
deleted_style = 'fg:#E04D27'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = 'fg:#E04D27'
conflicted = '${count}ï‘¯ '
ahead = '${count}â‡¡ '
behind = '${count}â‡£ '
diverged = 'â‡•${ahead_count}â‡¡${behind_count}â‡£ '
up_to_date = 'âœ“ '
untracked = '[${count}ï³‡ ](fg:red)' # 'ï° ' # '? '
stashed = '[${count}ï›¢ ](fg:#A52A2A)' # 'ğŸ“¦ '# 'î› ' # 'ï’‡ ' # 'îœ ' # 'î¬‰ ' 
modified = '[${count}ó°·‰ ](fg:#C8AC00)' # 'ğŸ“' # '! '
staged = '[${count}ïƒ‘ ](fg:green)' # '+ '
renamed = '${count}ï«¦ ' # 'ï—ˆ '
deleted = '${count}ï¯Š ' # 'ğŸ—‘ ' '- '
disabled = false

[jobs]
format = '[ î‚± ](fg:blue bold)[$number$symbol]($style)'
style = 'fg:blue'
symbol = 'ï¥­' # 'ïª‚' # 'ó°œ' # 'î®¢' # 'âœ¦'
symbol_threshold = 1
number_threshold = 4
disabled = false

[memory_usage]
format = '[ î‚± ](fg:purple bold)[$symbol ${ram} ${swap}]($style)'
style = 'fg:purple'
symbol = 'ï¬™ ï¥£' # 'ï¬™ ï§¥' # 'ï¬™ / ó°¾µ' # 'ó°› ó°¾µ' # 'ï¬™ ó°¾´' # 'ï¬™ ó°¾¶' # 'ï¬™ ó°¾·' 'ï¬™ ó°£‚'
threshold = 75
disabled = false

[cmd_duration]
format = '[î‚³ ï”Ÿ $duration ]($style)'
style = 'fg:yellow'
min_time = 500
disabled = false

[fill]
style = 'fg:#505050'
symbol = 'â”€'

[status]
format = '[$symbol$status $hex_status ï–› $signal_number-$signal_name ]($style)'
style = 'fg:red'
symbol = 'âœ˜ '
disabled = false

[localip]
format = '[$localipv4 ](fg:green bold)'
ssh_only = true
disabled = false


# maybe sometime useful:
# â•­ â•´ â•° â•´ î‚³ î‚± ï„„ ï„… ï™€ ï™ â‰º â‰» â¬ â­ â® â¯ â° â± îˆ€ îŠ… ï“ ï” ï‘½ ï‘  ï© ï© î‚· î‚µ ï«¦ âœ âŸ â¢ â¥ âª â½ â”‚ â”ƒ â•‘ â® ïœ„ îˆ– â•± â•² î‚» î‚¹ îƒ îƒƒ î˜’ îƒ‚ îƒ€ îƒ„ îƒ… îƒ† îƒ‡
# âˆ‘ ïƒ³ ï’š ï‚¢ ï–› ï– ï– ï–Ÿ ïƒ« ï€ ï‡· ï‡¶ ï‰» ï‰º ïµ ï™½ ïš ïš† ï®… ï«® ï«¯ î® ï…½ â‡’ ï£· ï¬ â‡’ ï¦ƒ âœ˜ âœ˜ âœ— ï”© ï”¥ âœ” âœ“ ï® ï   ï”¹ ïœ½ ï—¬ ï—­ ï„³ ï³ ï… ï ï’ îœ î› ï’‡ ï›¢ ï€™ ï‚®
# ï’€ ïŠ– îœˆ ïˆ ï¢ ï‡“ ï‡’ ï¡ ï‡¡ î—» îœ¥ ï™ ï‘¿ ï‡ ï‚ ï— î«¼ ï°–  ï¦– ï‘¯ ï†ˆ ï—£ î‰© ï•œ ï• ï•“ ï•” ï•Œ ï• â† â†‘ â†’ â†“ â†” â†• ï˜¼ ï˜½ ï˜» ï˜¾ â‡… â‡„ ïƒ¬ ï¥£ ï§¥ ïšº ïš» ïš¼ ï—º ï•‹ ïŸ ï‘¬ ï‰¢ ï§Ÿ ï° ï® ? ï’¨ ï¤ î‡ îˆ î˜ î˜” îˆ¤ 
# ï•¶ ï•· ï—— ï—˜ ï—– ï—• ï—ˆ ï­ ï—¢ ï£© ï£­ ï£® ï£¬ ï£« ï¡ ïª¿ ï¥” ï¯¢ ï Ÿ ï   ï³‰ ï¨© î˜®
# ï…° ï’œ ï¦— ï¦˜ ï©¤ ï„¾ ï ½ ï ¾ ï ¿ ï¡€ ï’› ï”Ÿ ï”  ï”¢ ï”£ ï˜ˆ ï™ ï¦± ï³“ ïµ ï’ ï€« ï€¬ ï•µ ïŠ‘ ï€” ïš¿ ï¯Š ï˜ ï† ï‡€ ï³‡  ï°€  ïƒ‘ îˆ¿ ï¬™ ï›º ï›¹ ïŸ‰ ï¡» ï£† ï¥­ ïª‚
# ïŒˆ î° ïª ï™ ïª’ ï™¢ ï™£ ï¦¿ ï™¦ ï™¡ ï’ ï³¼  


# aktuell nicht genutze Module:
#\
#$kubernetes$vcsh$fossil_branch$hg_branch$pijul_channel$docker_context$package$c\
#$cmake$cobol$daml$dart$deno$dotneti$elixir$ulm$erlang$fennel$golang$guix_shell\
#$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$php\
#$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$swift$terraform$vlang\
#$vagrant$zig$buf$nix_shell$conda$meson$spack$aws$gcloud$openstack$azure$crystal\
#$container$shell$env_var$battery$time$custom\
#\